// <auto-generated />
using DressApp.WebUi.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DressApp.WebUi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230313201257_migrat2")]
    partial class migrat2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DressApp.WebUi.Data.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminPassword")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("AdminRole")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("AdminUserName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DressApp.WebUi.Data.Models.Favori", b =>
                {
                    b.Property<int>("FavoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FavoriPrice")
                        .HasColumnType("float");

                    b.Property<int>("UrunSayisi")
                        .HasColumnType("int");

                    b.HasKey("FavoriId");

                    b.ToTable("Favoris");
                });

            modelBuilder.Entity("DressApp.WebUi.Data.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("FavoriAppovred")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStock")
                        .HasColumnType("int");

                    b.Property<int>("RayonId")
                        .HasColumnType("int");

                    b.Property<bool>("SepetAppovred")
                        .HasColumnType("bit");

                    b.Property<int>("StarNumber")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("RayonId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DressApp.WebUi.Data.Models.Rayon", b =>
                {
                    b.Property<int>("RayonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RayonDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RayonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("RayonId");

                    b.ToTable("Rayons");
                });

            modelBuilder.Entity("DressApp.WebUi.Data.Models.Sepet", b =>
                {
                    b.Property<int>("SepetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SepetImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SepetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Sepetprice")
                        .HasColumnType("float");

                    b.Property<int>("UrunSayisi")
                        .HasColumnType("int");

                    b.HasKey("SepetId");

                    b.ToTable("Sepets");
                });

            modelBuilder.Entity("DressApp.WebUi.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("UserUserName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DressApp.WebUi.Data.Models.Product", b =>
                {
                    b.HasOne("DressApp.WebUi.Data.Models.Rayon", "Rayon")
                        .WithMany("Products")
                        .HasForeignKey("RayonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
